/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author bachilak
 */
public class Historico extends javax.swing.JFrame {

    /**
     * Creates new form Historico
     */
    
    private Menu menu;
    
    DefaultListModel data;
    
    public Historico(Menu menu) {
        this.menu = menu; // Inicializar CalcularRotas
        initComponents();
        //carregarRotas(); // Atualizar jList1 com dados
        data = new DefaultListModel();
        
        setTitle("Calculadora de rotas");
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        
        
        jList1.setModel(data);
    }
    /**
    private void carregarRotas() {
        // Obter o resultado da rota
        String resultadoRota = calcularRotas.getResultadoRota();

        // Adicionar o resultado ao JList
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement(resultadoRota); // Adiciona o valor calculado
        jList1.setModel(model);
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnCarregarHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/back-icon.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setFocusable(false);
        jScrollPane1.setViewportView(jList1);

        btnCarregarHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarregarHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/loader-icon.png"))); // NOI18N
        btnCarregarHistorico.setText("Carregar histórico");
        btnCarregarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(86, 86, 86)
                .addComponent(btnCarregarHistorico)
                .addContainerGap(155, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCarregarHistorico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
        model.removeAllElements();
        this.setVisible(false);
        menu.setVisible(true);
      
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCarregarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarHistoricoActionPerformed
        //Botão carregar menu:
        //System.out.println(menu.calcularRotas.getHibtnCarregarHistorico));
        data.addAll(menu.calcularRotas.getHistorico());
    }//GEN-LAST:event_btnCarregarHistoricoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCarregarHistorico;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
